### PR TITLE
Update windows section

### PR DESCRIPTION
**Pull request by sandstrand**
Clarify which part of the solarus package is needed to avoid extracting sample quest and quest editor.

### CODE REVIEW

**Comment by mattias-p** [comment]
This is the developer documentation. They may have use for the quest editor, no?

**Comment by sandstrand** [comment]
They may, yes, but this is the "Playing Tuincs!" instruction.

As the quest editor is  a stand-alone executable and is in another folder in the package, any instruction for how to extract or use it would not change the instruction in this commit on how to play.

**Comment by mattias-p** [comment]
Since we'll provide another guide for people who just want to play (and point it out from this document), I think it'd be better to gear this document towards people who want to tinker with the game.

**Comment by sandstrand** [comment]
I would like to write as little documentation as possible which overlaps with the Solarus documentation, Usage of the quest editor is not something we have control over.

Plus, the quest editor has no installation, I don't know what I'd write about it.

**Pull request merged**
